global using Xunit;
global using Video_Streaming.Models;
global using Video_Streaming.Repositories.Interfaces;
global using Video_Streaming.Repositories;
global using Video_Streaming.Services.Interfaces;
global using Video_Streaming.Services;
global using Video_Streaming.Services.DTO;
global using Moq;
using System.IdentityModel.Tokens.Jwt;
using Microsoft.IdentityModel.Tokens;
using DotNetEnv;
using System.Security.Claims;
using System.Text;
